// This model was generated by Forest CLI. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/reference-guide/models/enrich-your-models

module.exports = (mongoose, Mongoose) => {
  // This section contains the properties of your model, mapped to your collection's properties.
  // Learn more here: https://docs.forestadmin.com/documentation/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const schema = Mongoose.Schema(
    {
      repeatEventDays: [String],
      helpForOrganizers: Boolean,
      hasReminderName: Boolean,
      reminderName: String,
      requestCoOrganizers: Boolean,
      coOrganizerRequests: [String],
      coOrganizerOffers: [String],
      coOrganizerGift: String,
      ages: [String],
      activityImage: String,
      infoLine: String,
      title: String,
      isOnline: Boolean,
      address: String,
      location: String,
      date: String,
      startTime: String,
      attendeeLimit: Number,
      hasPrice: Boolean,
      price: Number,
      ticketLink: String,
      topic: Number,
      description: String,
      howToFind: String,
      friendsOnly: Boolean,
      selectPeople: Boolean,
      allowPhoneNumberDisplay: Boolean,
      allowCoOrganiser: Boolean,
      repeatEvent: Boolean,
      repeatEventFrequency: String,
      parity: Boolean,
      parityValues: String,
      allowGuests: Boolean,
      howManyGuests: Number,
      ageRestriction: Boolean,
      createdAt: Date,
      updatedAt: Date,
    },
    {
      timestamps: true,
    }
  );

  return mongoose.model("activity", schema, "Activity");
};
