// This model was generated by Forest CLI. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/reference-guide/models/enrich-your-models

module.exports = (mongoose, Mongoose) => {
  // This section contains the properties of your model, mapped to your collection's properties.
  // Learn more here: https://docs.forestadmin.com/documentation/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const schema = Mongoose.Schema(
    {
      email: String,
      salt: String,
      token: String,
      hash: String,
      lastActionTime: Number,
      memberId: Number,
      avatar: String,
      city: String,
      firstName: String,
      isPersonalAccount: Boolean,
      lastName: String,
      nativeLanguage: String,
      sexe: String,
      userName: String,
      spokenLanguage: [Number],
      hobbies: [Number],
      phone: String,
      birthday: Number,
      children: Number,
      tobacco: Number,
      alcohol: Number,
      about: String,
      chats: [String],
      createdAt: Date,
      updatedAt: Date,
    },
    {
      timestamps: true,
    }
  );

  return mongoose.model("user", schema, "User");
};
